double-click middle button
StoyanDimitrov/middle-mouse-button-scroll pull request #7
Opened 2020-01-17 16:49 UTC by amirfru

Added an option to double-click the middle button to bypass the addon's function

2020-01-21 12:34 UTC, StoyanDimitrov commented
Thank you for your contribution. Unfortunately, I'm currently away. Will take handle this PR in the first weeks of the next month.

2020-02-13 07:52 UTC, StoyanDimitrov requested changes

2020-02-13 07:52 UTC, StoyanDimitrov commented on content_scripts/scroll.js
> +  let doubleClick_time = 500
Stick to the camel case notation.

2020-02-13 07:52 UTC, StoyanDimitrov commented on content_scripts/scroll.js
> +    if (doubleClick) {
Check for the real value here not a truthy one

2020-02-13 07:52 UTC, StoyanDimitrov commented on content_scripts/scroll.js
> +    {
Else case is unneeded here.

2020-02-13 07:52 UTC, StoyanDimitrov commented on content_scripts/scroll.js
> +        setTimeout(function(){ doubleClick = false }, doubleClick_time);
Use arrow function as the rest of the code

2020-02-13 07:54 UTC, StoyanDimitrov commented
Thank you for your patience.

2020-02-13 08:28 UTC, amirfru commented
No prob,
I've made the changes :)

2020-02-13 08:46 UTC, merged

2020-02-13 08:46 UTC, StoyanDimitrov commented
Thank you!

2020-02-13 11:04 UTC, amirfru commented
Sure, nice addon, cheers!